openapi: 3.2.0
info:
  version: 1.0.142
  x-ibm-name: ibm-watson-content-hub-api
  title: Acoustic Content Delivery resources API
  description: Copyright © Acoustic, L.P. 2023
tags:
- name: Delivery resources
  description: The Delivery Resource Service (DRS) provides access to the published resources in Akamai.
paths:
  /delivery/v1/resources:
    get:
      tags:
      - Delivery resources
      x-ibm-dx-security-user-roles:
      - admin
      - manager
      - editor
      - viewer
      - authenticatedVisitor
      - anonymous
      x-ibm-dx-vary: []
      summary: Retrieve a resource by path
      description: 'This endpoint retrieves the resource at the given path. Restricted resources cannot be accessed. To access those resources too, you have to use /mydelivery/v1/resources.

        The resource''s path can be obtained using the Authoring assets API: /authoring/v1/assets


        {

        "items": [

        {

        "mediaType": "image/jpeg",

        "name": "myPicture.jpg",

        "path": "/path/to/myPicture.jpg",

        ...


        The delivery URL for this endpoint would look like:


        /delivery/v1/resources?path=/path/to/myPicture.jpg


        **Note:** This endpoint should not be used for rendering published resources on a site, retrieving resources from Akamai directly is better optimized for this use case.


        To retrieve the resource directly from Akamai:


        https://[host]/[TenantID]/path/to/myPicture.jpg


        User roles: admin, manager, editor, viewer, authenticatedVisitor, anonymous'
      parameters:
      - name: path
        in: query
        description: Provide the absolute path of the resource (URL encoded).
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The requested resource.
          headers:
            Content-Type:
              description: Media type of resource.
              schema:
                type: string
          content:
            file:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
        '404':
          description: Not found
          content:
            file:
              schema:
                type: object
                properties:
                  service:
                    type: string
                    description: Service name.
                  requestId:
                    type: string
                    description: Request ID.
                  errors:
                    type: object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      level:
                        type: string
                      description:
                        type: string
                      locale:
                        type: string
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: string
                    description: Service name.
                  requestId:
                    type: string
                    description: Request ID.
                  errors:
                    type: object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      level:
                        type: string
                      description:
                        type: string
                      locale:
                        type: string
              example:
                service: prod-delivery-resource
                requestId: a0c938dd-ab79-4a7c-b124-5f8bc57bb657
                errors:
                  code: 3003
                  message: 'Path not found: {path}.'
                  level: ERROR
                  description: The resource at the specified path could not be found.
                  locale: en
        '429':
          description: Too Many Requests, the server has reached a limit, the request must be sent again at a later time.
          content:
            file:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Unexpected error
          content:
            file:
              schema:
                type: object
                properties:
                  service:
                    type: string
                    description: Service name.
                  requestId:
                    type: string
                    description: Request ID.
                  errors:
                    type: object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      level:
                        type: string
                      description:
                        type: string
                      locale:
                        type: string
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: string
                    description: Service name.
                  requestId:
                    type: string
                    description: Request ID.
                  errors:
                    type: object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      level:
                        type: string
                      description:
                        type: string
                      locale:
                        type: string
              example:
                service: prod-delivery-resource
                requestId: a0c938dd-ab79-4a7c-b124-5f8bc57bb657
                errors:
                  code: 1014
                  message: Unexpected error occurred.
                  level: ERROR
                  description: Unable to complete the request due to an unexpected error. Try again or contact Acoustic support if problem persists.
                  locale: en
      operationId: getDeliveryV1Resources
      x-operation-id-source: derived
  /delivery/v1/resources/{fileIdentifier}:
    get:
      tags:
      - Delivery resources
      x-ibm-dx-security-user-roles:
      - admin
      - manager
      - editor
      - viewer
      - authenticatedVisitor
      - anonymous
      x-ibm-dx-vary: []
      summary: Retrieve a resource by Id
      description: 'This endpoint retrieves the resource for the specified resource Id. Restricted resources cannot be accessed. To access those resources too, you have to use /mydelivery/v1/resources/{fileIdentifier}.

        The resource''s Id can be obtained using the Authoring assets API: /authoring/v1/assets


        {

        "items": [

        {

        "resource": "06763fa56ceec4d5bcafb37b53de2cd1",

        ...


        The delivery Url for this endpoint would look like:


        /delivery/v1/resources/06763fa56ceec4d5bcafb37b53de2cd1


        User roles: admin, manager, editor, viewer, authenticatedVisitor, anonymous'
      parameters:
      - name: fileIdentifier
        in: path
        description: 'Provide the resource Id of the resource to be retrieved.

          Optionally, if the extension (e.g. .jpg) is known then it can be appended to the id.

          '
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The requested resource.
          headers:
            Content-Type:
              description: Media type of resource.
              schema:
                type: string
          content:
            file:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
        '404':
          description: Not found
          content:
            file:
              schema:
                type: object
                properties:
                  service:
                    type: string
                    description: Service name.
                  requestId:
                    type: string
                    description: Request ID.
                  errors:
                    type: object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      level:
                        type: string
                      description:
                        type: string
                      locale:
                        type: string
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: string
                    description: Service name.
                  requestId:
                    type: string
                    description: Request ID.
                  errors:
                    type: object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      level:
                        type: string
                      description:
                        type: string
                      locale:
                        type: string
              example:
                service: prod-delivery-resource
                requestId: a0c938dd-ab79-4a7c-b124-5f8bc57bb657
                errors:
                  code: 3009
                  message: 'File not found for resourceId: {resourceId}.'
                  level: ERROR
                  description: The resource with the specified resourceId could not be found.
                  locale: en
        '429':
          description: Too Many Requests, the server has reached a limit, the request must be sent again at a later time.
          content:
            file:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Unexpected error
          content:
            file:
              schema:
                type: object
                properties:
                  service:
                    type: string
                    description: Service name.
                  requestId:
                    type: string
                    description: Request ID.
                  errors:
                    type: object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      level:
                        type: string
                      description:
                        type: string
                      locale:
                        type: string
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: string
                    description: Service name.
                  requestId:
                    type: string
                    description: Request ID.
                  errors:
                    type: object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      level:
                        type: string
                      description:
                        type: string
                      locale:
                        type: string
              example:
                service: prod-delivery-resource
                requestId: a0c938dd-ab79-4a7c-b124-5f8bc57bb657
                errors:
                  code: 1014
                  message: Unexpected error occurred.
                  level: ERROR
                  description: Unable to complete the request due to an unexpected error. Try again or contact Acoustic support if problem persists.
                  locale: en
      operationId: getDeliveryV1ResourcesByFileIdentifier
      x-operation-id-source: derived
components:
  schemas:
    ErrorResponse:
      description: This JSON record represents an error condition.
      type: object
      properties:
        errors:
          type: array
          items:
            description: This JSON record represents an individual error or warning contained in an error message.
            type: object
            properties:
              code:
                type: integer
                description: An error code
              message:
                type: string
                description: A message describing what went wrong.
              description:
                type: string
                description: Further explanation of the error condition and potential next steps to resolve the problem.
              more_info:
                type: string
                description: A URL pointing to a web site that provides more information on the given error condition.
              level:
                type: string
                enum:
                - ERROR
                - WARNING
                description: The severity level of the message. Default is error.
              parameters:
                type: object
                description: Additional properties reflecting the dynamic parts of the error condition.
              cause:
                type: object
                description: This property can be used to transport causing error message records produced by a down stream service calls.
              locale:
                type: string
                description: This property represents the locale of the text contained in properties 'message', and 'description'. This property is mandatory if message and description contain translated text.
            required:
            - code
            - message
        requestId:
          type: string
          description: The ID of the failing request.
        service:
          type: string
          description: The name of the service serving the error message.
      required:
      - errors
      - requestId
